/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinleetcode
import java.net.DatagramPacket
import java.net.DatagramSocket

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {

fun main(args: Array<String>) {
  // Create a DatagramSocket
  val socket = DatagramSocket()

  // Create a DatagramPacket
  val packet = DatagramPacket(
    "Hello, world!".toByteArray(),
    "Hello, world!".toByteArray().size,
    "127.0.0.1",
    8080
  )

  // Send the packet
  socket.send(packet)

  // Close the socket
  socket.close()
}

}
